### ISSUE TITLE
New Wizard Types

### ISSUE THREAD

**Issue by Lazzer64** [Lazzer64/COMP-55#2]
Create new Wizard Types with different gameplay effects.
The player will have the option to choose between four different wizards when starting a new game.
The three new wizards will include:

* Green Wizard: Does no damage if combo is below 3 but has a higher damage multiplier.
* Yellow Wizard: Does extra damage with Lightning, but does reduced damage with the other types.
* Blue Wizard: Matching Hearts does damage but does not heal.

This will require the addition of four new Java Classes one for each type of Wizard.
These new classes will extend the existing `Player` class which will become an abstract class.

In addition the way in which attacks are made must be rewritten.
Currently attacks are handled outside of the `Player` class and simply do damage based on a multiplier.
This will need to be changed to handle the attack in the implementations of the `Player` class based on the
match type and the combo number.

**Comment by onzfonz** [comment]
Work on this one.  Let me know if you have any questions.

**Comment by Lazzer64** [comment]
This feature is now implemented, to test the feature you can:
1. Launch the `Main` class as an applet
2. Click the start game button to enter the character select screen
3. Select any character (Green is the easiest to observe).
4. Observe the character's effect.
